schema_version = "1.0.0"

id = "skyrim_billboards"
version = "0.1.0"
name = "Skyrim Billboards"
tagline = "Aim NiBillboardNode objects at the camera"
maintainer = "Aerisarn <aerisarn@gmail.com>"
type = "add-on"

blender_version_min = "4.2.0"
license = ["SPDX:GPL-3.0-or-later"]

tags = ["Object"]
